### ISSUE TITLE
Up the Rainbow dependency to 4.0.0 and above?

### ISSUE THREAD

**Issue by mattyoung** [dominicegginton/spinner#46]
I tried changing: https://github.com/mattyoung/spinner

but I don't know why I get:

> /Users/matty/Devel/ArgumentParser/Projects/WebGrep/Sources/WebGrep.swift:93:19 Value of type 'Spinner' has no member 'updateText'

**Comment by mattyoung** [comment]
Ok, so these function were change to `message`, `success`, `error`. I see there is a 2.0.0 version but Rainbow still not set to version 4.0.0

**Comment by dominicegginton** [comment]
I have some time to update the dependency this weekend. Unless you would like to submit a PR I would be happy to review?

**Comment by dominicegginton** [comment]
Created a new that includes this: https://github.com/dominicegginton/spinner/releases/tag/2.1.0
